@echo off
echo Appending to .gitignore...
echo frontend/node_modules/ >> .gitignore
echo Resetting last commit...
git reset --soft HEAD~1
echo Removing node_modules from index...
git rm -r --cached frontend/node_modules
echo Committing changes...
git commit -m "Deploy scripts and tests (excluding node_modules)"
echo Pushing to origin...
git push -u origin main --force
echo Done.
